CREATE TABLE IF NOT EXISTS pilot(
    id SMALLINT UNSIGNED AUTO_INCREMENT,
    name_pil VARCHAR(50) NOT NULL,
    flying_hours MEDIUMINT NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS airplane(
    id SMALLINT UNSIGNED AUTO_INCREMENT,
    type VARCHAR(30) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS lobby(
    id SMALLINT UNSIGNED AUTO_INCREMENT,
    name_lobby VARCHAR(45) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS hangar(
    id SMALLINT UNSIGNED AUTO_INCREMENT,
    name_hangar VARCHAR(50) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS member(
    id INT UNSIGNED AUTO_INCREMENT,
    name_member VARCHAR(50) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS flight(
    id INT UNSIGNED AUTO_INCREMENT,
    origin VARCHAR(40) NOT NULL,
    destination VARCHAR(40) NOT NULL,
    hour TIME,
    date DATE,
    airplane_id SMALLINT UNSIGNED,
    lobby_id SMALLINT UNSIGNED,
    hangar_id SMALLINT UNSIGNED,
    PRIMARY KEY(id),
    FOREIGN KEY(airplane_id) REFERENCES airplane(id) ON DELETE NO ACTION,
    FOREIGN KEY(lobby_id) REFERENCES lobby(id) ON DELETE NO ACTION,
    FOREIGN KEY(hangar_id) REFERENCES hangar(id) ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS pilot_flight(
    pilot_id SMALLINT UNSIGNED,
    flight_id INT UNSIGNED,
    FOREIGN KEY(pilot_id) REFERENCES pilot(id) ON DELETE NO ACTION,
    FOREIGN KEY(flight_id) REFERENCES flight(id) ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS member_flight(
    member_id INT UNSIGNED,
    flight_id INT UNSIGNED,
    FOREIGN KEY(member_id) REFERENCES member(id) ON DELETE NO ACTION,
    FOREIGN KEY(flight_id) REFERENCES flight(id) ON DELETE NO ACTION
);